language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "sonarcloud"
    token:
      secure: "b63f47724a6d39740e83f4fc1078ff8ade87d0f9"

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  mvn sonar:sonar \
  -Dsonar.projectKey=chaosHD_test \
  -Dsonar.organization=chaoshd-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=b63f47724a6d39740e83f4fc1078ff8ade87d0f9

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
